spring:
  application:
    name: User-service
  data:
    cassandra:
      port: 9042
      keyspace-name: user_database
      schema-action: CREATE_IF_NOT_EXISTS
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      local-datacenter: datacenter1
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-deadcoder11u2.herokuapp.com/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-methods: GET
        allowed-origins: '*'
  endpoint:
    health:
      show-details: always
